# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awqTxDwP-UZ6IoaNCBYiqgEju6WcnEle
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px
import ta

st.title("📈 Stock Return Forecasting & Portfolio Optimization")

# Download stock data
df = yf.download("AAPL", start="2020-01-01", end="2023-01-01")
df["Returns"] = df["Close"].pct_change()
df["RSI"] = ta.momentum.RSIIndicator(df["Close"], window=14).rsi()

st.subheader("Raw Stock Data")
st.dataframe(df.tail())

st.subheader("Stock Price Trend")
fig = px.line(df, x=df.index, y="Close", title="Stock Closing Price")
st.plotly_chart(fig, use_container_width=True)

st.subheader("RSI Trend")
fig2 = px.line(df, x=df.index, y="RSI", title="RSI Trend")
st.plotly_chart(fig2, use_container_width=True)